// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: EmuBlue2Gauge

#ifndef _EMUBLUE2GAUGE_UI_H
#define _EMUBLUE2GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
void ui_event_Arc3( lv_event_t * e);
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_ImgButton1;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_N_RPM;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image7;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4( lv_event_t * e);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_2065062798);   // assets\fond nis d'abeille .png
LV_IMG_DECLARE( ui_img_jauge_rpm_png);   // assets\Jauge RPM.png
LV_IMG_DECLARE( ui_img_home_png);   // assets\Home.png
LV_IMG_DECLARE( ui_img_amesisproject_png);   // assets\AmesisProject.png
LV_IMG_DECLARE( ui_img_background1_png);   // assets\BackGround1.png
LV_IMG_DECLARE( ui_img_led_png);   // assets\Led.png
LV_IMG_DECLARE( ui_img_boutton_png);   // assets\boutton.png
LV_IMG_DECLARE( ui_img_gauge_png);   // assets\gauge.png
LV_IMG_DECLARE( ui_img_turbo_png);   // assets\turbo.png
LV_IMG_DECLARE( ui_img_afr_png);   // assets\afr.png
LV_IMG_DECLARE( ui_img_monlogo240_png);   // assets\MonLogo240.png
LV_IMG_DECLARE( ui_img_1703503159);   // assets\STRI-Xline-RPM_LRG2.png

LV_FONT_DECLARE( ui_font_Digit);
LV_FONT_DECLARE( ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
