// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: EmuBlue2Gauge

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_2065062798);
lv_obj_set_width( ui_Image1, 240);
lv_obj_set_height( ui_Image1, 240);
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc3 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc3, 235);
lv_obj_set_height( ui_Arc3, 235);
lv_obj_set_x( ui_Arc3, -1 );
lv_obj_set_y( ui_Arc3, 0 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc3, 0,7000);
lv_arc_set_value(ui_Arc3, 2500);
lv_arc_set_bg_angles(ui_Arc3,140,40);
lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Arc3, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc3, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_Arc3, &ui_img_jauge_rpm_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_pad_left(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
lv_obj_set_height( ui_ImgButton1, 36);
lv_obj_set_width( ui_ImgButton1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButton1, 1 );
lv_obj_set_y( ui_ImgButton1, 80 );
lv_obj_set_align( ui_ImgButton1, LV_ALIGN_CENTER );

ui_Image8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8, &ui_img_amesisproject_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, 0 );
lv_obj_set_y( ui_Image8, 45 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image9, &ui_img_jauge_rpm_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, 34);
lv_obj_set_height( ui_Label2, 14);
lv_obj_set_x( ui_Label2, -61 );
lv_obj_set_y( ui_Label2, 82 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"RPM");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_N_RPM = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_N_RPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_N_RPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_N_RPM, 0 );
lv_obj_set_y( ui_N_RPM, -20 );
lv_obj_set_align( ui_N_RPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_N_RPM,"1000");
lv_obj_set_style_text_color(ui_N_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_N_RPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_N_RPM, &lv_font_montserrat_46, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
