// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: EmuBlue2Gauge

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_Image3, &ui_img_gauge_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 205
lv_obj_set_x( ui_Image3, -1 );
lv_obj_set_y( ui_Image3, -18 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Image3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Image3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Screen3);
lv_img_set_src(ui_Image4, &ui_img_turbo_png);
lv_obj_set_width( ui_Image4, 496);
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_Image4, 15 );
lv_obj_set_y( ui_Image4, 15 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,150);
lv_obj_set_style_blend_mode(ui_Image4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Image4, 128, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
